<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="FB_Invoke" Id="{41eb7c5d-132f-4e51-bd5c-da9f681236c9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Invoke
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Invoke">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>